# Generated by Django 2.0.3 on 2018-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180322_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('not-specified', 'Not sepcified'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
