# Generated by Django 2.0.3 on 2018-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180331_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not sepcified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
