# Generated by Django 2.0.3 on 2018-04-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180401_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not sepcified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
