# Generated by Django 2.0.3 on 2018-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20181024_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('not-specified', 'Not sepcified'), ('female', 'Female')], max_length=80, null=True),
        ),
    ]
