# Generated by Django 2.0.3 on 2018-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20181030_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not sepcified'), ('female', 'Female'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
