# Generated by Django 2.0.3 on 2018-03-31 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20180331_0039'),
        ('notifications', '0002_auto_20180331_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='imgage',
        ),
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
