# Generated by Django 2.0.3 on 2018-10-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180401_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
