# Generated by Django 2.0.3 on 2018-10-23 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
