# Generated by Django 2.0.3 on 2018-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20181030_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(max_length=140),
        ),
    ]
