# Generated by Django 2.0.3 on 2018-10-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subway',
            new_name='Station',
        ),
    ]
