# Generated by Django 2.0.3 on 2018-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20181024_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fr_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='station',
            name='station_cd',
            field=models.CharField(max_length=40),
        ),
    ]
