# Generated by Django 2.0.3 on 2018-10-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20181024_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='fr_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='line_num',
            field=models.CharField(max_length=5),
        ),
    ]
