# Generated by Django 2.0.3 on 2018-10-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['station_nm']},
        ),
    ]
